#???
plc.browser=EDGE

plc.browser.keepOpen=true

# Baosky IDE ??
plc.ide.url=https://localhost:5571/

# PLCopen 文件根目录。默认使用随程序发布的 classpath 资源。
# 部署后可在外部 config/application.properties 中覆盖为实际磁盘目录。
plc.import.path=classpath:PLC_code
